"""``cadora deliverable`` — the client-facing consulting pack (WP-C2).

Turns one archived run into a narrative *delivery report* a consultant can hand
to a client: executive summary, what was delivered per AI-DLC phase, quality &
assurance, cost (FinOps), and an evidence appendix. It **reuses** ``report.py``'s
structured evidence (``build_report``) rather than re-deriving anything — the
evidence pack (``cadora report``) is the checksummed proof; this is the readable
story on top of it.

Markdown is the dependency-free core. ``.docx`` is an optional extra
(``pip install cadora[deliverable]``), soft-imported so the core install stays lean.

Honesty contract (inherited from the evidence pack): every claim is exactly what
the run archive recorded — deterministic gate verdicts, integrity findings,
human-review decisions, per-node cost (backend-reported or price-table estimate,
flagged) — checksummed, not signed.
"""

from __future__ import annotations

from pathlib import Path

from cadora.report import build_report


def _verdict(ok) -> str:
    return "✅ PASS" if ok else "❌ FAIL"


def _cost(v) -> str:
    return f"${v:.4f}" if v is not None else "—"


def render_deliverable(report: dict) -> str:
    """Render the delivery report markdown from a ``build_report`` dict."""
    run = report["run"]
    summary = report["summary"]
    ev = report.get("evidence_pack", {})
    nodes = report["nodes"]
    run_id = run.get("run_id")
    backends = ", ".join(summary.get("backends") or [str(run.get("executor"))])
    gates = ", ".join(f"{k}: {v}" for k, v in (summary.get("gates") or {}).items()) or "no gated nodes"
    est = summary.get("estimated_cost_nodes", 0)
    reviews = summary.get("human_review_decisions", 0)
    findings = summary.get("integrity_findings", 0)

    lines: list[str] = []
    lines.append(f"# Solution Delivery Report — {run.get('topology')}")
    lines.append("")
    lines.append(
        f"*Run `{run_id}` · generated by Cadora {ev.get('cadora_version', '')} · "
        f"{ev.get('generated_at', '')}*"
    )
    lines.append("")

    # Executive summary
    lines.append("## Executive summary")
    lines.append("")
    lines.append(
        f"Cadora conducted an AI-DLC pipeline (**{run.get('topology')}**) across "
        f"**{summary.get('nodes')} nodes** on **{backends}**. "
        f"Outcome: **{_verdict(run.get('ok'))}**. "
        f"Total metered cost **{_cost(summary.get('cost_usd'))}**"
        + (f" ({est} node(s) priced from the public price table)" if est else "")
        + f". Gate verdicts — {gates}. "
        f"Integrity findings: {findings}. Human-review decisions: {reviews}."
    )
    lines.append("")

    # What was delivered
    lines.append("## What was delivered")
    lines.append("")
    lines.append("| Node | Backend | Model | Outcome | Gate | Cost |")
    lines.append("|------|---------|-------|---------|------|------|")
    for n in nodes:
        g = n.get("gate") or {}
        gate_cell = (g.get("status") or ("passed" if g.get("passed") else "—")) if g else "—"
        cost = _cost(n.get("cost_usd")) + ("*" if n.get("cost_estimated") else "")
        lines.append(
            f"| {n.get('node_id')} | {n.get('executor') or '—'} | {n.get('model') or '—'} "
            f"| {'✓' if n.get('ok') else '✗'} | {gate_cell} | {cost} |"
        )
    if est:
        lines.append("")
        lines.append("<sub>`*` = cost estimated from the public price table (backend reported tokens, not dollars).</sub>")
    lines.append("")

    # Quality & assurance
    lines.append("## Quality & assurance")
    lines.append("")
    lines.append(f"- **Gate verdicts:** {gates}")
    lines.append(
        f"- **Integrity:** {findings} finding(s) across "
        f"{summary.get('integrity_failed_nodes', 0)} node(s)"
    )
    lines.append(f"- **Human review:** {reviews} recorded decision(s)")
    lines.append(
        f"- **Verifiable evidence:** every claim above is checksummed — run "
        f"`cadora report {run_id}` for the portable, SHA-256-verified evidence pack."
    )
    lines.append("")

    # Cost / FinOps
    lines.append("## Cost (FinOps)")
    lines.append("")
    lines.append(
        f"Total: **{_cost(summary.get('cost_usd'))}** across {summary.get('nodes')} nodes"
        + (f", {est} estimated from the price table." if est else ".")
    )
    lines.append("")

    # Evidence appendix
    lines.append("## Evidence appendix")
    lines.append("")
    lines.append(
        f"- {len(report.get('artifacts') or [])} archived file(s), each SHA-256 checksummed."
    )
    lines.append(
        "- Honesty contract: this report claims exactly what the run archive recorded "
        "(gate verdicts, integrity findings, human-review decisions, per-node cost); "
        "it is checksummed, not signed, and makes no claim about agent honesty beyond "
        "what the gates and integrity checks verified."
    )
    lines.append("")
    return "\n".join(lines)


def build_deliverable(run_dir: str | Path) -> str:
    """Build the delivery-report markdown for one archived run directory."""
    return render_deliverable(build_report(run_dir))


def _render_docx(md_report: dict, out_path: Path) -> Path:
    """Optional .docx rendering. Requires the ``deliverable`` extra (python-docx)."""
    try:
        from docx import Document  # type: ignore
    except ImportError as exc:  # pragma: no cover - exercised only without the extra
        raise SystemExit(
            "cadora deliverable --docx requires python-docx: pip install 'cadora[deliverable]'"
        ) from exc

    run = md_report["run"]
    summary = md_report["summary"]
    doc = Document()
    doc.add_heading(f"Solution Delivery Report — {run.get('topology')}", level=0)
    doc.add_paragraph(f"Run {run.get('run_id')} · outcome {_verdict(run.get('ok'))}")
    doc.add_heading("Executive summary", level=1)
    doc.add_paragraph(
        f"AI-DLC pipeline across {summary.get('nodes')} nodes on "
        f"{', '.join(summary.get('backends') or [])}. "
        f"Total metered cost {_cost(summary.get('cost_usd'))}."
    )
    doc.add_heading("What was delivered", level=1)
    table = doc.add_table(rows=1, cols=5)
    hdr = table.rows[0].cells
    for i, h in enumerate(("Node", "Backend", "Model", "Outcome", "Cost")):
        hdr[i].text = h
    for n in md_report["nodes"]:
        row = table.add_row().cells
        row[0].text = str(n.get("node_id"))
        row[1].text = str(n.get("executor") or "—")
        row[2].text = str(n.get("model") or "—")
        row[3].text = "pass" if n.get("ok") else "fail"
        row[4].text = _cost(n.get("cost_usd"))
    doc.save(out_path)
    return out_path


def write_deliverable(
    run_dir: str | Path, out: str | Path | None = None, *, docx: bool = False
) -> dict:
    """Write ``deliverable.md`` (and optionally ``deliverable.docx``) for a run."""
    run_dir = Path(run_dir)
    report = build_report(run_dir)
    out_dir = Path(out) if out else run_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "deliverable.md"
    md_path.write_text(render_deliverable(report), encoding="utf-8")
    paths = {"md": md_path}
    if docx:
        paths["docx"] = _render_docx(report, out_dir / "deliverable.docx")
    return paths
